'''
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        hash = {}
        
        for char in s:
            if char not in hash: 
                hash[char] = 1
            else: 
                hash[char] += 1
                
        for char in t: 
            if char not in hash: 
                return char 
            if char in hash: 
                hash[char] -= 1 
                if hash[char] < 0: 
                    return char 
